squash!

diff --git a/packaging/assets/init/rethinkdb b/packaging/assets/init/rethinkdb
--- a/packaging/assets/init/rethinkdb
+++ b/packaging/assets/init/rethinkdb
@@ -14,27 +14,19 @@
 # Description:       This looks in /etc/rethinkdb/instances.d for rethinkdb config files and launches, stops, or examines each instance described there.
 ### END INIT INFO
 
-itask="$1"
+set -x
+set -e -u
+
+itask="${1:-}"
 
 rtdbbin=/usr/bin/rethinkdb ;
 rtdbconfigdir=/etc/rethinkdb ;
 
-ini_section () {
-    local _t1="${1#\[}"
-    local _t2="${_t1%]}"
-    if [ "$_t1" = "$1" -o "$_t2" = "$_t1" ]; then
-        false
-    else
-        read -r $2 <<EOF
-`echo $_t2`
-EOF
-    fi
-}
-
-ini_setting () {
-    local _val="${1#*:}"
-    local _key="${1%%:*}"
-    if [ "$_key" = "" ]; then
+# parse a line form the config file
+conf_read_line () {
+    local _val="${1#*=}"
+    local _key="${1%%=*}"
+    if [ "$_val" = "$1" ]; then
         false
     else
         read -r $2 <<EOF
@@ -46,113 +38,165 @@ EOF
     fi
 }
 
-ini_read () {
-    local section=""
-    local dict="#"
+# conf_read <file> <var>
+# read the config file file into the variable var
+conf_read () {
+    local _dict="#"
     local n=1
     local line sect key val
     while read -r line; do
         line=${line%%#*}
-        if ini_section "$line" sect; then
-            section=$sect
-        elif ini_setting "$line" key val; then
-            if [ "$section" = "" ]; then
-                dict="$dict$key=$val#"
-            else
-                dict="$dict$section.$key=$val#"
-            fi
+        if conf_read_line "$line" key val; then
+            _dict="$_dict$key=$val#"
         elif [ "`echo -n $line`" != "" ]; then
-            echo ini_read: $1: parse error on line $n >&2
+            echo "$0: $1: parse error on line $n" >&2
             return 1
         fi
         n=$((n + 1))
     done < $1 && read -r $2 <<EOF
-$dict
+$_dict
 EOF
 }
 
-ini_data_get () {
-    local valp="${1#*#$2=}"
-    local val="${valp%%#*}"
-    if [ "$valp" = "$1" ]; then
+# get <conf> <key> [var]
+# extract the value of key from the parsed config conf
+# into the variable var or if var is not passed, into the variable key
+get () {
+    local _valp="${1#*#$2=}"
+    local _val="${_valp%%#*}"
+    if [ "$_valp" = "$1" ]; then
         return 1
     else
-        read -r $3 <<EOF
-$val
+        read -r ${3:-$2} <<EOF
+$_val
 EOF
     fi
 }
 
+# is_running <pid>
+# test if the process exists
+is_running () {
+    ps -p "$1" > /dev/null
+}
 
-if [ "$itask" = "" ] ;
-then
-	echo "Usage: /etc/init.d/rethinkdb COMMAND" ;
-else
-	# We check for active configurations .
-	if [ -e "$rtdbconfigdir"/instances.d/*.conf ] ;
-	then
-		for rtdbconffile in "$rtdbconfigdir"/instances.d/*.conf ;
-		do
-			# We check for instructions about which user and group ought to run the service .
-			runuser="" ;
-			rungroup="" ;
-			if [ -e "$rtdbconffile" ] ;
-			then
-				runuser="`cat "$rtdbconffile" | grep '^[ \t]*runuser[ \t]*\=' | head -n 1 | sed -e 's/^\([ \ta-zA-Z0-9]\|[-]\)*\=[ \t]*//g'`" ;
-				rungroup="`cat "$rtdbconffile" | grep '^[ \t]*rungroup[ \t]*\=' | head -n 1 | sed -e 's/^\([ \ta-zA-Z0-9]\|[-]\)*\=[ \t]*//g'`" ;
-			fi ;
-			useropt="" ;
-			if [ "$runuser" != "" ] ;
-			then
-				useropt="--chuid" ;
-			fi ;
-			groupopt="" ;
-			if [ "$runuser" != "" ] ;
-			then
-				groupopt="--group" ;
-			fi ;
-			# We seek the pid-file .
-			rtdbpidfile="`cat "$rtdbconffile" | grep '^[ \t]*pid-file[ \t]*\=' | head -n 1 | sed -e 's/^\([ \ta-zA-Z0-9]\|[-]\)*\=[ \t]*//g'`" ;
-			if [ "$itask" = "stop" ] || [ "$itask" = "restart" ] || [ "$itask" = "reload" ] || [ "$itask" = "force-reload" ] ;
-			then
-				if [ ! -e "$rtdbpidfile" ] ;
-				then
-					echo "rethinkdb:""$rtdbconffile"": The instance is not running (there is no pid file)" ;
-				else
-					start-stop-daemon --stop --pidfile "$rtdbpidfile" --signal INT "$useropt" "$runuser" "$groupopt" "$rungroup" ;
-				fi ;
-			fi ;
-			if [ "$itask" = "start" ] || [ "$itask" = "restart" ] || [ "$itask" = "reload" ] || [ "$itask" = "force-reload" ] ;
-			then
-				if [ -e /var/run ] && [ "`echo "$rtdbpidfile" | grep '^/var/run'`" != "" ] ;
-				then
-					mkdir -p "`dirname "$rtdbpidfile"`" ;
-				fi ;
-				if [ -e "$rtdbpidfile" ] ;
-				then
-					echo "rethinkdb:""$rtdbconffile"": The instance has already started" ;
-					echo "rethinkdb: To force the instance to start, delete \`$rtdbpidfile'" ;
-				else
-					start-stop-daemon --start --pidfile "$rtdbpidfile" "$useropt" "$runuser" "$groupopt" "$rungroup" --startas "$rtdbbin" --background -- --config-file="$rtdbconffile" ;
-				fi ;
-			fi ;
-			if [ "$itask" = "status" ] ;
-			then
-				if [ -e "$rtdbpidfile" ] ;
-				then
-					if [ "`ps -Af | awk 'BEGIN { inited = 0 ; pidpos = 0 ; } { if ( inited == 0 ) { count1 = 0 ; while ( count1 < NF ) { count1 ++ ; if ( $count1 ~ /^[Pp][Ii][Dd]$/ ) { pidpos = count1 ; inited = 1 ; } } } else { printf "%s\n" , $pidpos ; } }' | grep '^'"\`cat \"$rtdbpidfile\"\`"'$'`" = "" ] ;
-					then
-						echo "rethinkdb:""$rtdbconffile"" stop/crashed" ;
-					else
-						echo "rethinkdb:""$rtdbconffile"" start/running, pid `cat $rtdbpidfile | grep '^[0-9]*$'`" ;
-					fi ;
-				else
-					echo "rethinkdb:""$rtdbconffile"" stop/waiting" ;
-				fi ;
-			fi ;
-		done ;
+
+# simple automatic allocation of ports
+next_free_port_offset () {
+    port=0
+    if ! ls "$rtdbconfigdir"/instances.d/.*.port-offset >/dev/null 2>/dev/null ; then
+        echo $port
+        return
+    fi
+    for file in "$rtdbconfigdir"/instances.d/.*.port-offset ; do
+        next="`cat "$file"`"
+        if [ "$port" -le "$next" ]; then
+            port="$((next + 1))"
+        fi
+    done
+    echo "$port"
+}
+
+if [ "$itask" = "" ] ; then
+	echo "Usage: /etc/init.d/rethinkdb [start|stop|restart|force-restart|status]" ;
+        exit 1
+fi
+
+# We check for active configurations .
+if ! ls "$rtdbconfigdir"/instances.d/*.conf >/dev/null 2>/dev/null ; then
+	echo "rethinkdb: No instances defined in $rtdbconfigdir/instances.d/"
+	echo "rethinkdb: See http://www.rethinkdb.com/docs/guides/startup/ for more information" ;
+        exit
+fi
+
+for rtdbconffile in "$rtdbconfigdir"/instances.d/*.conf ;
+do
+    if ! conf_read "$rtdbconffile" conf; then
+        continue
+    fi
+
+    instance_name=`basename "$rtdbconffile" .conf`
+
+    set -- # empty $@
+
+    get "$conf" runuser  && set -- "$@" --chuid "$runuser"
+    
+    get "$conf" rungroup && set -- "$@" --group "$rungroup"
+
+    set -- "$@" -- --config-file="$rtdbconffile"
+
+    if ! get "$conf" pid-file rtdbpidfile; then
+        rtdbpidfile="/var/run/rethinkdb/$instance_name/pid_file"
+        parent_directory="`dirname "$rtdbpidfile"`"
+        if [ ! -e "$parent_directory" ]; then
+            mkdir "$parent_directory" && \
+                ( test -n "${runuser:-}"  && chown -- "$runuser"  "$parent_directory" ) && \
+                ( test -n "${rungroup:-}" && chgrp -- "$rungroup" "$parent_directory" )
+        fi
+    fi
+    set -- "$@" --pid-file "$rtdbpidfile"
+
+    if ! get "$conf" rtdb_directory; then
+        rtdb_directory="/var/lib/rethinkdb/$instance_name/data"
+        parent_directory="/var/lib/rethinkdb/$instance_name"
+        if [ ! -e "$parent_directory" ]; then
+            mkdir "$parent_directory" && \
+                ( test -n "${runuser:-}"  && chown -- "$runuser"  "$parent_directory" ) && \
+                ( test -n "${rungroup:-}" && chgrp -- "$rungroup" "$parent_directory" )
+        fi
+        set -- "$@" --directory "$rtdb_directory" 
+    fi
+
+    # if no port is specified in the config file, automatically
+    # generate a port-offset for this instance and save it
+    if ! (get "$conf" driver-port x || get "$conf" cluster-port x ||
+          get "$conf" http-port   x || get "$conf" port-offset  x ); then
+        
+        port_file="$rtdbconfigdir/instances.d/.$instance_name.port-offset"
+        
+        if [ -e "$port_file" ]; then
+            set -- "$@" --port-offset "`cat "$port_file"`"
+        else
+            port_offset="`next_free_port_offset`"
+            echo "$port_offset" > "$port_file"
+            set -- "$@" --port-offset "$port_offset"
+        fi
+    fi
+
+    if [ "$itask" = "stop" -o "$itask" = "restart" -o "$itask" = "restart" -o "$itask" = "force-restart" ] ; then
+	if [ ! -e "$rtdbpidfile" ] ; then
+	    echo "rethinkdb: $instance_name: The instance is not running (there is no pid file)"
+	elif [ is_running "`cat "rtdbpidfile"`" ] ; then
+            kill -INT "`cat "$rtdbpidfile"`"
+        else
+            rm -f "$rtdbpidfile"
+	fi
+    fi
+
+    if [ "$itask" = "start" -o "$itask" = "restart" -o "$itask" = "restart" -o "$itask" = "force-restart" ] ; then
+	if [ -e /var/run -a "${rtdbpidfile#/var/run}" != "$rtdbpidfile" ] ; then
+	    mkdir -p "`dirname "$rtdbpidfile"`"
+	fi
+
+	if [ -e "$rtdbpidfile" ] && is_running "$(cat "$rtdbpidfile")"; then
+	    echo "rethinkdb: $instance_name: The instance has already started"
 	else
-		echo "rethinkdb: 0 instances in ""$rtdbconfigdir""/instances.d"
-		echo "rethinkdb: See http://www.rethinkdb.com/docs/guides/startup/ for more information" ;
-	fi ;
-fi ;
+            if [ -e "$rtdbpidfile" ] ; then
+                rm "$rtdbpidfile"
+            fi
+            echo "rethinkdb: $instance_name: Starting instance. (logging to \`$rtdb_directory/log_file')"
+	    start-stop-daemon --start --pidfile "$rtdbpidfile" --startas "$rtdbbin" --background "$@"
+        fi
+    fi
+
+    if [ "$itask" = "status" ] ; then
+	if [ -e "$rtdbpidfile" ] ; then
+	    if ! is_running "$(cat "$rtdbpidfile")"; then
+		echo "rethinkdb: $instance_name: stop/crashed"
+	    else
+		echo "rethinkdb: $instance_name: start/running, pid `cat "$rtdbpidfile"`"
+	    fi
+	else
+	    echo "rethinkdb: $instance_name: stop/waiting"
+	fi
+    fi
+done
